/* 
 * RESTAPI Service
 *
 * RESTful API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// getAllOrganizations account
        /// </summary>
        /// <remarks>
        /// Returns all organizations belonging to the account
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>AccountStoredOrganizationResponseCollection</returns>
        AccountStoredOrganizationResponseCollection AccountGetAllOrganizations (string authorization);

        /// <summary>
        /// getAllOrganizations account
        /// </summary>
        /// <remarks>
        /// Returns all organizations belonging to the account
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>ApiResponse of AccountStoredOrganizationResponseCollection</returns>
        ApiResponse<AccountStoredOrganizationResponseCollection> AccountGetAllOrganizationsWithHttpInfo (string authorization);
        /// <summary>
        /// getOrganizationById account
        /// </summary>
        /// <remarks>
        /// Returns information about the specified account
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">ID of the organization whose information should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>AccountGetOrganizationByIDResponseBody</returns>
        AccountGetOrganizationByIDResponseBody AccountGetOrganizationById (int? organizationId, string authorization);

        /// <summary>
        /// getOrganizationById account
        /// </summary>
        /// <remarks>
        /// Returns information about the specified account
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">ID of the organization whose information should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>ApiResponse of AccountGetOrganizationByIDResponseBody</returns>
        ApiResponse<AccountGetOrganizationByIDResponseBody> AccountGetOrganizationByIdWithHttpInfo (int? organizationId, string authorization);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// getAllOrganizations account
        /// </summary>
        /// <remarks>
        /// Returns all organizations belonging to the account
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of AccountStoredOrganizationResponseCollection</returns>
        System.Threading.Tasks.Task<AccountStoredOrganizationResponseCollection> AccountGetAllOrganizationsAsync (string authorization);

        /// <summary>
        /// getAllOrganizations account
        /// </summary>
        /// <remarks>
        /// Returns all organizations belonging to the account
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of ApiResponse (AccountStoredOrganizationResponseCollection)</returns>
        System.Threading.Tasks.Task<ApiResponse<AccountStoredOrganizationResponseCollection>> AccountGetAllOrganizationsAsyncWithHttpInfo (string authorization);
        /// <summary>
        /// getOrganizationById account
        /// </summary>
        /// <remarks>
        /// Returns information about the specified account
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">ID of the organization whose information should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of AccountGetOrganizationByIDResponseBody</returns>
        System.Threading.Tasks.Task<AccountGetOrganizationByIDResponseBody> AccountGetOrganizationByIdAsync (int? organizationId, string authorization);

        /// <summary>
        /// getOrganizationById account
        /// </summary>
        /// <remarks>
        /// Returns information about the specified account
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">ID of the organization whose information should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of ApiResponse (AccountGetOrganizationByIDResponseBody)</returns>
        System.Threading.Tasks.Task<ApiResponse<AccountGetOrganizationByIDResponseBody>> AccountGetOrganizationByIdAsyncWithHttpInfo (int? organizationId, string authorization);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AccountApi : IAccountApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AccountApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AccountApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// getAllOrganizations account Returns all organizations belonging to the account
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>AccountStoredOrganizationResponseCollection</returns>
        public AccountStoredOrganizationResponseCollection AccountGetAllOrganizations (string authorization)
        {
             ApiResponse<AccountStoredOrganizationResponseCollection> localVarResponse = AccountGetAllOrganizationsWithHttpInfo(authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// getAllOrganizations account Returns all organizations belonging to the account
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>ApiResponse of AccountStoredOrganizationResponseCollection</returns>
        public ApiResponse< AccountStoredOrganizationResponseCollection > AccountGetAllOrganizationsWithHttpInfo (string authorization)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling AccountApi->AccountGetAllOrganizations");

            var localVarPath = "/account/organization";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (jwt_header_Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AccountGetAllOrganizations", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AccountStoredOrganizationResponseCollection>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AccountStoredOrganizationResponseCollection) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AccountStoredOrganizationResponseCollection)));
        }

        /// <summary>
        /// getAllOrganizations account Returns all organizations belonging to the account
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of AccountStoredOrganizationResponseCollection</returns>
        public async System.Threading.Tasks.Task<AccountStoredOrganizationResponseCollection> AccountGetAllOrganizationsAsync (string authorization)
        {
             ApiResponse<AccountStoredOrganizationResponseCollection> localVarResponse = await AccountGetAllOrganizationsAsyncWithHttpInfo(authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// getAllOrganizations account Returns all organizations belonging to the account
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of ApiResponse (AccountStoredOrganizationResponseCollection)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AccountStoredOrganizationResponseCollection>> AccountGetAllOrganizationsAsyncWithHttpInfo (string authorization)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling AccountApi->AccountGetAllOrganizations");

            var localVarPath = "/account/organization";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (jwt_header_Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AccountGetAllOrganizations", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AccountStoredOrganizationResponseCollection>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AccountStoredOrganizationResponseCollection) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AccountStoredOrganizationResponseCollection)));
        }

        /// <summary>
        /// getOrganizationById account Returns information about the specified account
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">ID of the organization whose information should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>AccountGetOrganizationByIDResponseBody</returns>
        public AccountGetOrganizationByIDResponseBody AccountGetOrganizationById (int? organizationId, string authorization)
        {
             ApiResponse<AccountGetOrganizationByIDResponseBody> localVarResponse = AccountGetOrganizationByIdWithHttpInfo(organizationId, authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// getOrganizationById account Returns information about the specified account
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">ID of the organization whose information should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>ApiResponse of AccountGetOrganizationByIDResponseBody</returns>
        public ApiResponse< AccountGetOrganizationByIDResponseBody > AccountGetOrganizationByIdWithHttpInfo (int? organizationId, string authorization)
        {
            // verify the required parameter 'organizationId' is set
            if (organizationId == null)
                throw new ApiException(400, "Missing required parameter 'organizationId' when calling AccountApi->AccountGetOrganizationById");
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling AccountApi->AccountGetOrganizationById");

            var localVarPath = "/account/organization/{organizationId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (organizationId != null) localVarPathParams.Add("organizationId", this.Configuration.ApiClient.ParameterToString(organizationId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (jwt_header_Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AccountGetOrganizationById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AccountGetOrganizationByIDResponseBody>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AccountGetOrganizationByIDResponseBody) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AccountGetOrganizationByIDResponseBody)));
        }

        /// <summary>
        /// getOrganizationById account Returns information about the specified account
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">ID of the organization whose information should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of AccountGetOrganizationByIDResponseBody</returns>
        public async System.Threading.Tasks.Task<AccountGetOrganizationByIDResponseBody> AccountGetOrganizationByIdAsync (int? organizationId, string authorization)
        {
             ApiResponse<AccountGetOrganizationByIDResponseBody> localVarResponse = await AccountGetOrganizationByIdAsyncWithHttpInfo(organizationId, authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// getOrganizationById account Returns information about the specified account
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="organizationId">ID of the organization whose information should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of ApiResponse (AccountGetOrganizationByIDResponseBody)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AccountGetOrganizationByIDResponseBody>> AccountGetOrganizationByIdAsyncWithHttpInfo (int? organizationId, string authorization)
        {
            // verify the required parameter 'organizationId' is set
            if (organizationId == null)
                throw new ApiException(400, "Missing required parameter 'organizationId' when calling AccountApi->AccountGetOrganizationById");
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling AccountApi->AccountGetOrganizationById");

            var localVarPath = "/account/organization/{organizationId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (organizationId != null) localVarPathParams.Add("organizationId", this.Configuration.ApiClient.ParameterToString(organizationId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (jwt_header_Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("AccountGetOrganizationById", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AccountGetOrganizationByIDResponseBody>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AccountGetOrganizationByIDResponseBody) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(AccountGetOrganizationByIDResponseBody)));
        }

    }
}
