/* 
 * RESTAPI Service
 *
 * RESTful API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDevicelogApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// getDeviceLogs devicelog
        /// </summary>
        /// <remarks>
        /// Returns up to 100 new logs from the specified device
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="DeviceChildIdDefunct">ID of the device whose log counters should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <param name="lastDeliveredId">ID of the oldest log counter from which to start returning samples (optional)</param>
        /// <returns>DevicelogStoredDeviceLogResponseCollection</returns>
        DevicelogStoredDeviceLogResponseCollection DevicelogGetDeviceLogs (int? DeviceChildIdDefunct, string authorization, int? lastDeliveredId = null);

        /// <summary>
        /// getDeviceLogs devicelog
        /// </summary>
        /// <remarks>
        /// Returns up to 100 new logs from the specified device
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="DeviceChildIdDefunct">ID of the device whose log counters should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <param name="lastDeliveredId">ID of the oldest log counter from which to start returning samples (optional)</param>
        /// <returns>ApiResponse of DevicelogStoredDeviceLogResponseCollection</returns>
        ApiResponse<DevicelogStoredDeviceLogResponseCollection> DevicelogGetDeviceLogsWithHttpInfo (int? DeviceChildIdDefunct, string authorization, int? lastDeliveredId = null);
        /// <summary>
        /// getLastDeviceLog devicelog
        /// </summary>
        /// <remarks>
        /// Returns information about the last known log record from the specified device
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="DeviceChildIdDefunct">ID of the device whose last log counters should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>DevicelogStoredDeviceLogResponseCollection</returns>
        DevicelogStoredDeviceLogResponseCollection DevicelogGetLastDeviceLog (int? DeviceChildIdDefunct, string authorization);

        /// <summary>
        /// getLastDeviceLog devicelog
        /// </summary>
        /// <remarks>
        /// Returns information about the last known log record from the specified device
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="DeviceChildIdDefunct">ID of the device whose last log counters should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>ApiResponse of DevicelogStoredDeviceLogResponseCollection</returns>
        ApiResponse<DevicelogStoredDeviceLogResponseCollection> DevicelogGetLastDeviceLogWithHttpInfo (int? DeviceChildIdDefunct, string authorization);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// getDeviceLogs devicelog
        /// </summary>
        /// <remarks>
        /// Returns up to 100 new logs from the specified device
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="DeviceChildIdDefunct">ID of the device whose log counters should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <param name="lastDeliveredId">ID of the oldest log counter from which to start returning samples (optional)</param>
        /// <returns>Task of DevicelogStoredDeviceLogResponseCollection</returns>
        System.Threading.Tasks.Task<DevicelogStoredDeviceLogResponseCollection> DevicelogGetDeviceLogsAsync (int? DeviceChildIdDefunct, string authorization, int? lastDeliveredId = null);

        /// <summary>
        /// getDeviceLogs devicelog
        /// </summary>
        /// <remarks>
        /// Returns up to 100 new logs from the specified device
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="DeviceChildIdDefunct">ID of the device whose log counters should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <param name="lastDeliveredId">ID of the oldest log counter from which to start returning samples (optional)</param>
        /// <returns>Task of ApiResponse (DevicelogStoredDeviceLogResponseCollection)</returns>
        System.Threading.Tasks.Task<ApiResponse<DevicelogStoredDeviceLogResponseCollection>> DevicelogGetDeviceLogsAsyncWithHttpInfo (int? DeviceChildIdDefunct, string authorization, int? lastDeliveredId = null);
        /// <summary>
        /// getLastDeviceLog devicelog
        /// </summary>
        /// <remarks>
        /// Returns information about the last known log record from the specified device
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="DeviceChildIdDefunct">ID of the device whose last log counters should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of DevicelogStoredDeviceLogResponseCollection</returns>
        System.Threading.Tasks.Task<DevicelogStoredDeviceLogResponseCollection> DevicelogGetLastDeviceLogAsync (int? DeviceChildIdDefunct, string authorization);

        /// <summary>
        /// getLastDeviceLog devicelog
        /// </summary>
        /// <remarks>
        /// Returns information about the last known log record from the specified device
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="DeviceChildIdDefunct">ID of the device whose last log counters should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of ApiResponse (DevicelogStoredDeviceLogResponseCollection)</returns>
        System.Threading.Tasks.Task<ApiResponse<DevicelogStoredDeviceLogResponseCollection>> DevicelogGetLastDeviceLogAsyncWithHttpInfo (int? DeviceChildIdDefunct, string authorization);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DevicelogApi : IDevicelogApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DevicelogApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DevicelogApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DevicelogApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DevicelogApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// getDeviceLogs devicelog Returns up to 100 new logs from the specified device
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="DeviceChildIdDefunct">ID of the device whose log counters should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <param name="lastDeliveredId">ID of the oldest log counter from which to start returning samples (optional)</param>
        /// <returns>DevicelogStoredDeviceLogResponseCollection</returns>
        public DevicelogStoredDeviceLogResponseCollection DevicelogGetDeviceLogs (int? DeviceChildIdDefunct, string authorization, int? lastDeliveredId = null)
        {
             ApiResponse<DevicelogStoredDeviceLogResponseCollection> localVarResponse = DevicelogGetDeviceLogsWithHttpInfo(DeviceChildIdDefunct, authorization, lastDeliveredId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// getDeviceLogs devicelog Returns up to 100 new logs from the specified device
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="DeviceChildIdDefunct">ID of the device whose log counters should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <param name="lastDeliveredId">ID of the oldest log counter from which to start returning samples (optional)</param>
        /// <returns>ApiResponse of DevicelogStoredDeviceLogResponseCollection</returns>
        public ApiResponse< DevicelogStoredDeviceLogResponseCollection > DevicelogGetDeviceLogsWithHttpInfo (int? DeviceChildIdDefunct, string authorization, int? lastDeliveredId = null)
        {
            // verify the required parameter 'DeviceChildIdDefunct' is set
            if (DeviceChildIdDefunct == null)
                throw new ApiException(400, "Missing required parameter 'DeviceChildIdDefunct' when calling DevicelogApi->DevicelogGetDeviceLogs");
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling DevicelogApi->DevicelogGetDeviceLogs");

            var localVarPath = "/device/{DeviceChildIdDefunct}/log";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (DeviceChildIdDefunct != null) localVarPathParams.Add("DeviceChildIdDefunct", this.Configuration.ApiClient.ParameterToString(DeviceChildIdDefunct)); // path parameter
            if (lastDeliveredId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "lastDeliveredId", lastDeliveredId)); // query parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (jwt_header_Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DevicelogGetDeviceLogs", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DevicelogStoredDeviceLogResponseCollection>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DevicelogStoredDeviceLogResponseCollection) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DevicelogStoredDeviceLogResponseCollection)));
        }

        /// <summary>
        /// getDeviceLogs devicelog Returns up to 100 new logs from the specified device
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="DeviceChildIdDefunct">ID of the device whose log counters should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <param name="lastDeliveredId">ID of the oldest log counter from which to start returning samples (optional)</param>
        /// <returns>Task of DevicelogStoredDeviceLogResponseCollection</returns>
        public async System.Threading.Tasks.Task<DevicelogStoredDeviceLogResponseCollection> DevicelogGetDeviceLogsAsync (int? DeviceChildIdDefunct, string authorization, int? lastDeliveredId = null)
        {
             ApiResponse<DevicelogStoredDeviceLogResponseCollection> localVarResponse = await DevicelogGetDeviceLogsAsyncWithHttpInfo(DeviceChildIdDefunct, authorization, lastDeliveredId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// getDeviceLogs devicelog Returns up to 100 new logs from the specified device
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="DeviceChildIdDefunct">ID of the device whose log counters should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <param name="lastDeliveredId">ID of the oldest log counter from which to start returning samples (optional)</param>
        /// <returns>Task of ApiResponse (DevicelogStoredDeviceLogResponseCollection)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DevicelogStoredDeviceLogResponseCollection>> DevicelogGetDeviceLogsAsyncWithHttpInfo (int? DeviceChildIdDefunct, string authorization, int? lastDeliveredId = null)
        {
            // verify the required parameter 'DeviceChildIdDefunct' is set
            if (DeviceChildIdDefunct == null)
                throw new ApiException(400, "Missing required parameter 'DeviceChildIdDefunct' when calling DevicelogApi->DevicelogGetDeviceLogs");
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling DevicelogApi->DevicelogGetDeviceLogs");

            var localVarPath = "/device/{DeviceChildIdDefunct}/log";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (DeviceChildIdDefunct != null) localVarPathParams.Add("DeviceChildIdDefunct", this.Configuration.ApiClient.ParameterToString(DeviceChildIdDefunct)); // path parameter
            if (lastDeliveredId != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "lastDeliveredId", lastDeliveredId)); // query parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (jwt_header_Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DevicelogGetDeviceLogs", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DevicelogStoredDeviceLogResponseCollection>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DevicelogStoredDeviceLogResponseCollection) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DevicelogStoredDeviceLogResponseCollection)));
        }

        /// <summary>
        /// getLastDeviceLog devicelog Returns information about the last known log record from the specified device
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="DeviceChildIdDefunct">ID of the device whose last log counters should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>DevicelogStoredDeviceLogResponseCollection</returns>
        public DevicelogStoredDeviceLogResponseCollection DevicelogGetLastDeviceLog (int? DeviceChildIdDefunct, string authorization)
        {
             ApiResponse<DevicelogStoredDeviceLogResponseCollection> localVarResponse = DevicelogGetLastDeviceLogWithHttpInfo(DeviceChildIdDefunct, authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// getLastDeviceLog devicelog Returns information about the last known log record from the specified device
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="DeviceChildIdDefunct">ID of the device whose last log counters should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>ApiResponse of DevicelogStoredDeviceLogResponseCollection</returns>
        public ApiResponse< DevicelogStoredDeviceLogResponseCollection > DevicelogGetLastDeviceLogWithHttpInfo (int? DeviceChildIdDefunct, string authorization)
        {
            // verify the required parameter 'DeviceChildIdDefunct' is set
            if (DeviceChildIdDefunct == null)
                throw new ApiException(400, "Missing required parameter 'DeviceChildIdDefunct' when calling DevicelogApi->DevicelogGetLastDeviceLog");
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling DevicelogApi->DevicelogGetLastDeviceLog");

            var localVarPath = "/device/{DeviceChildIdDefunct}/lastLog";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (DeviceChildIdDefunct != null) localVarPathParams.Add("DeviceChildIdDefunct", this.Configuration.ApiClient.ParameterToString(DeviceChildIdDefunct)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (jwt_header_Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DevicelogGetLastDeviceLog", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DevicelogStoredDeviceLogResponseCollection>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DevicelogStoredDeviceLogResponseCollection) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DevicelogStoredDeviceLogResponseCollection)));
        }

        /// <summary>
        /// getLastDeviceLog devicelog Returns information about the last known log record from the specified device
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="DeviceChildIdDefunct">ID of the device whose last log counters should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of DevicelogStoredDeviceLogResponseCollection</returns>
        public async System.Threading.Tasks.Task<DevicelogStoredDeviceLogResponseCollection> DevicelogGetLastDeviceLogAsync (int? DeviceChildIdDefunct, string authorization)
        {
             ApiResponse<DevicelogStoredDeviceLogResponseCollection> localVarResponse = await DevicelogGetLastDeviceLogAsyncWithHttpInfo(DeviceChildIdDefunct, authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// getLastDeviceLog devicelog Returns information about the last known log record from the specified device
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="DeviceChildIdDefunct">ID of the device whose last log counters should be returned</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of ApiResponse (DevicelogStoredDeviceLogResponseCollection)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DevicelogStoredDeviceLogResponseCollection>> DevicelogGetLastDeviceLogAsyncWithHttpInfo (int? DeviceChildIdDefunct, string authorization)
        {
            // verify the required parameter 'DeviceChildIdDefunct' is set
            if (DeviceChildIdDefunct == null)
                throw new ApiException(400, "Missing required parameter 'DeviceChildIdDefunct' when calling DevicelogApi->DevicelogGetLastDeviceLog");
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling DevicelogApi->DevicelogGetLastDeviceLog");

            var localVarPath = "/device/{DeviceChildIdDefunct}/lastLog";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (DeviceChildIdDefunct != null) localVarPathParams.Add("DeviceChildIdDefunct", this.Configuration.ApiClient.ParameterToString(DeviceChildIdDefunct)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (jwt_header_Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DevicelogGetLastDeviceLog", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DevicelogStoredDeviceLogResponseCollection>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DevicelogStoredDeviceLogResponseCollection) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DevicelogStoredDeviceLogResponseCollection)));
        }

    }
}
