/* 
 * RESTAPI Service
 *
 * RESTful API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IThresholdApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// getThresholdByStream threshold
        /// </summary>
        /// <remarks>
        /// Get thresholds for specified stream Id
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>ThresholdGetThresholdByStreamResponseBody</returns>
        ThresholdGetThresholdByStreamResponseBody ThresholdGetThresholdByStream (int? streamId, string authorization);

        /// <summary>
        /// getThresholdByStream threshold
        /// </summary>
        /// <remarks>
        /// Get thresholds for specified stream Id
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>ApiResponse of ThresholdGetThresholdByStreamResponseBody</returns>
        ApiResponse<ThresholdGetThresholdByStreamResponseBody> ThresholdGetThresholdByStreamWithHttpInfo (int? streamId, string authorization);
        /// <summary>
        /// getThresholdStatus threshold
        /// </summary>
        /// <remarks>
        /// Get thresholds for specified stream Id
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>ThresholdGetThresholdStatusResponseBody</returns>
        ThresholdGetThresholdStatusResponseBody ThresholdGetThresholdStatus (int? streamId, string authorization);

        /// <summary>
        /// getThresholdStatus threshold
        /// </summary>
        /// <remarks>
        /// Get thresholds for specified stream Id
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>ApiResponse of ThresholdGetThresholdStatusResponseBody</returns>
        ApiResponse<ThresholdGetThresholdStatusResponseBody> ThresholdGetThresholdStatusWithHttpInfo (int? streamId, string authorization);
        /// <summary>
        /// setThresholdByStream threshold
        /// </summary>
        /// <remarks>
        /// Set thresholds for specified stream Id
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <param name="setThresholdByStreamRequestBody"></param>
        /// <returns></returns>
        void ThresholdSetThresholdByStream (int? streamId, string authorization, ThresholdSetThresholdByStreamRequestBody setThresholdByStreamRequestBody);

        /// <summary>
        /// setThresholdByStream threshold
        /// </summary>
        /// <remarks>
        /// Set thresholds for specified stream Id
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <param name="setThresholdByStreamRequestBody"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> ThresholdSetThresholdByStreamWithHttpInfo (int? streamId, string authorization, ThresholdSetThresholdByStreamRequestBody setThresholdByStreamRequestBody);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// getThresholdByStream threshold
        /// </summary>
        /// <remarks>
        /// Get thresholds for specified stream Id
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of ThresholdGetThresholdByStreamResponseBody</returns>
        System.Threading.Tasks.Task<ThresholdGetThresholdByStreamResponseBody> ThresholdGetThresholdByStreamAsync (int? streamId, string authorization);

        /// <summary>
        /// getThresholdByStream threshold
        /// </summary>
        /// <remarks>
        /// Get thresholds for specified stream Id
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of ApiResponse (ThresholdGetThresholdByStreamResponseBody)</returns>
        System.Threading.Tasks.Task<ApiResponse<ThresholdGetThresholdByStreamResponseBody>> ThresholdGetThresholdByStreamAsyncWithHttpInfo (int? streamId, string authorization);
        /// <summary>
        /// getThresholdStatus threshold
        /// </summary>
        /// <remarks>
        /// Get thresholds for specified stream Id
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of ThresholdGetThresholdStatusResponseBody</returns>
        System.Threading.Tasks.Task<ThresholdGetThresholdStatusResponseBody> ThresholdGetThresholdStatusAsync (int? streamId, string authorization);

        /// <summary>
        /// getThresholdStatus threshold
        /// </summary>
        /// <remarks>
        /// Get thresholds for specified stream Id
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of ApiResponse (ThresholdGetThresholdStatusResponseBody)</returns>
        System.Threading.Tasks.Task<ApiResponse<ThresholdGetThresholdStatusResponseBody>> ThresholdGetThresholdStatusAsyncWithHttpInfo (int? streamId, string authorization);
        /// <summary>
        /// setThresholdByStream threshold
        /// </summary>
        /// <remarks>
        /// Set thresholds for specified stream Id
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <param name="setThresholdByStreamRequestBody"></param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task ThresholdSetThresholdByStreamAsync (int? streamId, string authorization, ThresholdSetThresholdByStreamRequestBody setThresholdByStreamRequestBody);

        /// <summary>
        /// setThresholdByStream threshold
        /// </summary>
        /// <remarks>
        /// Set thresholds for specified stream Id
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <param name="setThresholdByStreamRequestBody"></param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> ThresholdSetThresholdByStreamAsyncWithHttpInfo (int? streamId, string authorization, ThresholdSetThresholdByStreamRequestBody setThresholdByStreamRequestBody);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ThresholdApi : IThresholdApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ThresholdApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ThresholdApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ThresholdApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ThresholdApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// getThresholdByStream threshold Get thresholds for specified stream Id
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>ThresholdGetThresholdByStreamResponseBody</returns>
        public ThresholdGetThresholdByStreamResponseBody ThresholdGetThresholdByStream (int? streamId, string authorization)
        {
             ApiResponse<ThresholdGetThresholdByStreamResponseBody> localVarResponse = ThresholdGetThresholdByStreamWithHttpInfo(streamId, authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// getThresholdByStream threshold Get thresholds for specified stream Id
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>ApiResponse of ThresholdGetThresholdByStreamResponseBody</returns>
        public ApiResponse< ThresholdGetThresholdByStreamResponseBody > ThresholdGetThresholdByStreamWithHttpInfo (int? streamId, string authorization)
        {
            // verify the required parameter 'streamId' is set
            if (streamId == null)
                throw new ApiException(400, "Missing required parameter 'streamId' when calling ThresholdApi->ThresholdGetThresholdByStream");
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling ThresholdApi->ThresholdGetThresholdByStream");

            var localVarPath = "/stream/{streamId}/threshold";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (streamId != null) localVarPathParams.Add("streamId", this.Configuration.ApiClient.ParameterToString(streamId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (jwt_header_Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ThresholdGetThresholdByStream", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ThresholdGetThresholdByStreamResponseBody>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ThresholdGetThresholdByStreamResponseBody) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ThresholdGetThresholdByStreamResponseBody)));
        }

        /// <summary>
        /// getThresholdByStream threshold Get thresholds for specified stream Id
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of ThresholdGetThresholdByStreamResponseBody</returns>
        public async System.Threading.Tasks.Task<ThresholdGetThresholdByStreamResponseBody> ThresholdGetThresholdByStreamAsync (int? streamId, string authorization)
        {
             ApiResponse<ThresholdGetThresholdByStreamResponseBody> localVarResponse = await ThresholdGetThresholdByStreamAsyncWithHttpInfo(streamId, authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// getThresholdByStream threshold Get thresholds for specified stream Id
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of ApiResponse (ThresholdGetThresholdByStreamResponseBody)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ThresholdGetThresholdByStreamResponseBody>> ThresholdGetThresholdByStreamAsyncWithHttpInfo (int? streamId, string authorization)
        {
            // verify the required parameter 'streamId' is set
            if (streamId == null)
                throw new ApiException(400, "Missing required parameter 'streamId' when calling ThresholdApi->ThresholdGetThresholdByStream");
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling ThresholdApi->ThresholdGetThresholdByStream");

            var localVarPath = "/stream/{streamId}/threshold";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (streamId != null) localVarPathParams.Add("streamId", this.Configuration.ApiClient.ParameterToString(streamId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (jwt_header_Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ThresholdGetThresholdByStream", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ThresholdGetThresholdByStreamResponseBody>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ThresholdGetThresholdByStreamResponseBody) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ThresholdGetThresholdByStreamResponseBody)));
        }

        /// <summary>
        /// getThresholdStatus threshold Get thresholds for specified stream Id
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>ThresholdGetThresholdStatusResponseBody</returns>
        public ThresholdGetThresholdStatusResponseBody ThresholdGetThresholdStatus (int? streamId, string authorization)
        {
             ApiResponse<ThresholdGetThresholdStatusResponseBody> localVarResponse = ThresholdGetThresholdStatusWithHttpInfo(streamId, authorization);
             return localVarResponse.Data;
        }

        /// <summary>
        /// getThresholdStatus threshold Get thresholds for specified stream Id
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>ApiResponse of ThresholdGetThresholdStatusResponseBody</returns>
        public ApiResponse< ThresholdGetThresholdStatusResponseBody > ThresholdGetThresholdStatusWithHttpInfo (int? streamId, string authorization)
        {
            // verify the required parameter 'streamId' is set
            if (streamId == null)
                throw new ApiException(400, "Missing required parameter 'streamId' when calling ThresholdApi->ThresholdGetThresholdStatus");
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling ThresholdApi->ThresholdGetThresholdStatus");

            var localVarPath = "/stream/{streamId}/threshold/status";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (streamId != null) localVarPathParams.Add("streamId", this.Configuration.ApiClient.ParameterToString(streamId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (jwt_header_Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ThresholdGetThresholdStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ThresholdGetThresholdStatusResponseBody>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ThresholdGetThresholdStatusResponseBody) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ThresholdGetThresholdStatusResponseBody)));
        }

        /// <summary>
        /// getThresholdStatus threshold Get thresholds for specified stream Id
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of ThresholdGetThresholdStatusResponseBody</returns>
        public async System.Threading.Tasks.Task<ThresholdGetThresholdStatusResponseBody> ThresholdGetThresholdStatusAsync (int? streamId, string authorization)
        {
             ApiResponse<ThresholdGetThresholdStatusResponseBody> localVarResponse = await ThresholdGetThresholdStatusAsyncWithHttpInfo(streamId, authorization);
             return localVarResponse.Data;

        }

        /// <summary>
        /// getThresholdStatus threshold Get thresholds for specified stream Id
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <returns>Task of ApiResponse (ThresholdGetThresholdStatusResponseBody)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ThresholdGetThresholdStatusResponseBody>> ThresholdGetThresholdStatusAsyncWithHttpInfo (int? streamId, string authorization)
        {
            // verify the required parameter 'streamId' is set
            if (streamId == null)
                throw new ApiException(400, "Missing required parameter 'streamId' when calling ThresholdApi->ThresholdGetThresholdStatus");
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling ThresholdApi->ThresholdGetThresholdStatus");

            var localVarPath = "/stream/{streamId}/threshold/status";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (streamId != null) localVarPathParams.Add("streamId", this.Configuration.ApiClient.ParameterToString(streamId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter

            // authentication (jwt_header_Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ThresholdGetThresholdStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ThresholdGetThresholdStatusResponseBody>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ThresholdGetThresholdStatusResponseBody) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(ThresholdGetThresholdStatusResponseBody)));
        }

        /// <summary>
        /// setThresholdByStream threshold Set thresholds for specified stream Id
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <param name="setThresholdByStreamRequestBody"></param>
        /// <returns></returns>
        public void ThresholdSetThresholdByStream (int? streamId, string authorization, ThresholdSetThresholdByStreamRequestBody setThresholdByStreamRequestBody)
        {
             ThresholdSetThresholdByStreamWithHttpInfo(streamId, authorization, setThresholdByStreamRequestBody);
        }

        /// <summary>
        /// setThresholdByStream threshold Set thresholds for specified stream Id
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <param name="setThresholdByStreamRequestBody"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> ThresholdSetThresholdByStreamWithHttpInfo (int? streamId, string authorization, ThresholdSetThresholdByStreamRequestBody setThresholdByStreamRequestBody)
        {
            // verify the required parameter 'streamId' is set
            if (streamId == null)
                throw new ApiException(400, "Missing required parameter 'streamId' when calling ThresholdApi->ThresholdSetThresholdByStream");
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling ThresholdApi->ThresholdSetThresholdByStream");
            // verify the required parameter 'setThresholdByStreamRequestBody' is set
            if (setThresholdByStreamRequestBody == null)
                throw new ApiException(400, "Missing required parameter 'setThresholdByStreamRequestBody' when calling ThresholdApi->ThresholdSetThresholdByStream");

            var localVarPath = "/stream/{streamId}/threshold";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (streamId != null) localVarPathParams.Add("streamId", this.Configuration.ApiClient.ParameterToString(streamId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (setThresholdByStreamRequestBody != null && setThresholdByStreamRequestBody.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(setThresholdByStreamRequestBody); // http body (model) parameter
            }
            else
            {
                localVarPostBody = setThresholdByStreamRequestBody; // byte array
            }

            // authentication (jwt_header_Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ThresholdSetThresholdByStream", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// setThresholdByStream threshold Set thresholds for specified stream Id
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <param name="setThresholdByStreamRequestBody"></param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task ThresholdSetThresholdByStreamAsync (int? streamId, string authorization, ThresholdSetThresholdByStreamRequestBody setThresholdByStreamRequestBody)
        {
             await ThresholdSetThresholdByStreamAsyncWithHttpInfo(streamId, authorization, setThresholdByStreamRequestBody);

        }

        /// <summary>
        /// setThresholdByStream threshold Set thresholds for specified stream Id
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="streamId">Stream Id</param>
        /// <param name="authorization">JWT used for authentication</param>
        /// <param name="setThresholdByStreamRequestBody"></param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> ThresholdSetThresholdByStreamAsyncWithHttpInfo (int? streamId, string authorization, ThresholdSetThresholdByStreamRequestBody setThresholdByStreamRequestBody)
        {
            // verify the required parameter 'streamId' is set
            if (streamId == null)
                throw new ApiException(400, "Missing required parameter 'streamId' when calling ThresholdApi->ThresholdSetThresholdByStream");
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling ThresholdApi->ThresholdSetThresholdByStream");
            // verify the required parameter 'setThresholdByStreamRequestBody' is set
            if (setThresholdByStreamRequestBody == null)
                throw new ApiException(400, "Missing required parameter 'setThresholdByStreamRequestBody' when calling ThresholdApi->ThresholdSetThresholdByStream");

            var localVarPath = "/stream/{streamId}/threshold";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (streamId != null) localVarPathParams.Add("streamId", this.Configuration.ApiClient.ParameterToString(streamId)); // path parameter
            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (setThresholdByStreamRequestBody != null && setThresholdByStreamRequestBody.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(setThresholdByStreamRequestBody); // http body (model) parameter
            }
            else
            {
                localVarPostBody = setThresholdByStreamRequestBody; // byte array
            }

            // authentication (jwt_header_Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ThresholdSetThresholdByStream", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

    }
}
