/* 
 * RESTAPI Service
 *
 * RESTful API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// GetChannelByIdResponseBody result type (default view)
    /// </summary>
    [DataContract]
    public partial class ChannelGetChannelByIDResponseBody :  IEquatable<ChannelGetChannelByIDResponseBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChannelGetChannelByIDResponseBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ChannelGetChannelByIDResponseBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ChannelGetChannelByIDResponseBody" /> class.
        /// </summary>
        /// <param name="creationDate">Creation date (required).</param>
        /// <param name="DeviceChildIdDefunct">Device ID (required).</param>
        /// <param name="displayName">Channel name (required).</param>
        /// <param name="displayStatusName">Status name (required).</param>
        /// <param name="id">ID is the unique id of the channel. (required).</param>
        /// <param name="onDeviceId">On device number (required).</param>
        /// <param name="statusId">Status ID (required).</param>
        /// <param name="typeDisplayName">Type name (required).</param>
        /// <param name="typeId">Type ID (required).</param>
        public ChannelGetChannelByIDResponseBody(DateTime? creationDate = default(DateTime?), int? DeviceChildIdDefunct = default(int?), string displayName = default(string), string displayStatusName = default(string), long? id = default(long?), long? onDeviceId = default(long?), int? statusId = default(int?), string typeDisplayName = default(string), int? typeId = default(int?))
        {
            // to ensure "creationDate" is required (not null)
            if (creationDate == null)
            {
                throw new InvalidDataException("creationDate is a required property for ChannelGetChannelByIDResponseBody and cannot be null");
            }
            else
            {
                this.CreationDate = creationDate;
            }
            // to ensure "DeviceChildIdDefunct" is required (not null)
            if (DeviceChildIdDefunct == null)
            {
                throw new InvalidDataException("DeviceChildIdDefunct is a required property for ChannelGetChannelByIDResponseBody and cannot be null");
            }
            else
            {
                this.DeviceChildIdDefunct = DeviceChildIdDefunct;
            }
            // to ensure "displayName" is required (not null)
            if (displayName == null)
            {
                throw new InvalidDataException("displayName is a required property for ChannelGetChannelByIDResponseBody and cannot be null");
            }
            else
            {
                this.DisplayName = displayName;
            }
            // to ensure "displayStatusName" is required (not null)
            if (displayStatusName == null)
            {
                throw new InvalidDataException("displayStatusName is a required property for ChannelGetChannelByIDResponseBody and cannot be null");
            }
            else
            {
                this.DisplayStatusName = displayStatusName;
            }
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for ChannelGetChannelByIDResponseBody and cannot be null");
            }
            else
            {
                this.Id = id;
            }
            // to ensure "onDeviceId" is required (not null)
            if (onDeviceId == null)
            {
                throw new InvalidDataException("onDeviceId is a required property for ChannelGetChannelByIDResponseBody and cannot be null");
            }
            else
            {
                this.OnDeviceId = onDeviceId;
            }
            // to ensure "statusId" is required (not null)
            if (statusId == null)
            {
                throw new InvalidDataException("statusId is a required property for ChannelGetChannelByIDResponseBody and cannot be null");
            }
            else
            {
                this.StatusId = statusId;
            }
            // to ensure "typeDisplayName" is required (not null)
            if (typeDisplayName == null)
            {
                throw new InvalidDataException("typeDisplayName is a required property for ChannelGetChannelByIDResponseBody and cannot be null");
            }
            else
            {
                this.TypeDisplayName = typeDisplayName;
            }
            // to ensure "typeId" is required (not null)
            if (typeId == null)
            {
                throw new InvalidDataException("typeId is a required property for ChannelGetChannelByIDResponseBody and cannot be null");
            }
            else
            {
                this.TypeId = typeId;
            }
        }
        
        /// <summary>
        /// Creation date
        /// </summary>
        /// <value>Creation date</value>
        [DataMember(Name="creation_date", EmitDefaultValue=false)]
        public DateTime? CreationDate { get; set; }

        /// <summary>
        /// Device ID
        /// </summary>
        /// <value>Device ID</value>
        [DataMember(Name="device_id", EmitDefaultValue=false)]
        public int? DeviceChildIdDefunct { get; set; }

        /// <summary>
        /// Channel name
        /// </summary>
        /// <value>Channel name</value>
        [DataMember(Name="display_name", EmitDefaultValue=false)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Status name
        /// </summary>
        /// <value>Status name</value>
        [DataMember(Name="display_status_name", EmitDefaultValue=false)]
        public string DisplayStatusName { get; set; }

        /// <summary>
        /// ID is the unique id of the channel.
        /// </summary>
        /// <value>ID is the unique id of the channel.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public long? Id { get; set; }

        /// <summary>
        /// On device number
        /// </summary>
        /// <value>On device number</value>
        [DataMember(Name="on_device_num", EmitDefaultValue=false)]
        public long? OnDeviceId { get; set; }

        /// <summary>
        /// Status ID
        /// </summary>
        /// <value>Status ID</value>
        [DataMember(Name="status_id", EmitDefaultValue=false)]
        public int? StatusId { get; set; }

        /// <summary>
        /// Type name
        /// </summary>
        /// <value>Type name</value>
        [DataMember(Name="type_display_name", EmitDefaultValue=false)]
        public string TypeDisplayName { get; set; }

        /// <summary>
        /// Type ID
        /// </summary>
        /// <value>Type ID</value>
        [DataMember(Name="type_id", EmitDefaultValue=false)]
        public int? TypeId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ChannelGetChannelByIDResponseBody {\n");
            sb.Append("  CreationDate: ").Append(CreationDate).Append("\n");
            sb.Append("  DeviceChildIdDefunct: ").Append(DeviceChildIdDefunct).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  DisplayStatusName: ").Append(DisplayStatusName).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  OnDeviceId: ").Append(OnDeviceId).Append("\n");
            sb.Append("  StatusId: ").Append(StatusId).Append("\n");
            sb.Append("  TypeDisplayName: ").Append(TypeDisplayName).Append("\n");
            sb.Append("  TypeId: ").Append(TypeId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ChannelGetChannelByIDResponseBody);
        }

        /// <summary>
        /// Returns true if ChannelGetChannelByIDResponseBody instances are equal
        /// </summary>
        /// <param name="input">Instance of ChannelGetChannelByIDResponseBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ChannelGetChannelByIDResponseBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CreationDate == input.CreationDate ||
                    (this.CreationDate != null &&
                    this.CreationDate.Equals(input.CreationDate))
                ) && 
                (
                    this.DeviceChildIdDefunct == input.DeviceChildIdDefunct ||
                    (this.DeviceChildIdDefunct != null &&
                    this.DeviceChildIdDefunct.Equals(input.DeviceChildIdDefunct))
                ) && 
                (
                    this.DisplayName == input.DisplayName ||
                    (this.DisplayName != null &&
                    this.DisplayName.Equals(input.DisplayName))
                ) && 
                (
                    this.DisplayStatusName == input.DisplayStatusName ||
                    (this.DisplayStatusName != null &&
                    this.DisplayStatusName.Equals(input.DisplayStatusName))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.OnDeviceId == input.OnDeviceId ||
                    (this.OnDeviceId != null &&
                    this.OnDeviceId.Equals(input.OnDeviceId))
                ) && 
                (
                    this.StatusId == input.StatusId ||
                    (this.StatusId != null &&
                    this.StatusId.Equals(input.StatusId))
                ) && 
                (
                    this.TypeDisplayName == input.TypeDisplayName ||
                    (this.TypeDisplayName != null &&
                    this.TypeDisplayName.Equals(input.TypeDisplayName))
                ) && 
                (
                    this.TypeId == input.TypeId ||
                    (this.TypeId != null &&
                    this.TypeId.Equals(input.TypeId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CreationDate != null)
                    hashCode = hashCode * 59 + this.CreationDate.GetHashCode();
                if (this.DeviceChildIdDefunct != null)
                    hashCode = hashCode * 59 + this.DeviceChildIdDefunct.GetHashCode();
                if (this.DisplayName != null)
                    hashCode = hashCode * 59 + this.DisplayName.GetHashCode();
                if (this.DisplayStatusName != null)
                    hashCode = hashCode * 59 + this.DisplayStatusName.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.OnDeviceId != null)
                    hashCode = hashCode * 59 + this.OnDeviceId.GetHashCode();
                if (this.StatusId != null)
                    hashCode = hashCode * 59 + this.StatusId.GetHashCode();
                if (this.TypeDisplayName != null)
                    hashCode = hashCode * 59 + this.TypeDisplayName.GetHashCode();
                if (this.TypeId != null)
                    hashCode = hashCode * 59 + this.TypeId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DeviceChildIdDefunct (int?) minimum
            if(this.DeviceChildIdDefunct < (int?)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DeviceChildIdDefunct, must be a value greater than or equal to 1.", new [] { "DeviceChildIdDefunct" });
            }

            // DisplayName (string) maxLength
            if(this.DisplayName != null && this.DisplayName.Length > 256)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DisplayName, length must be less than 256.", new [] { "DisplayName" });
            }

            // DisplayStatusName (string) maxLength
            if(this.DisplayStatusName != null && this.DisplayStatusName.Length > 64)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DisplayStatusName, length must be less than 64.", new [] { "DisplayStatusName" });
            }

            // StatusId (int?) minimum
            if(this.StatusId < (int?)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for StatusId, must be a value greater than or equal to 1.", new [] { "StatusId" });
            }

            // TypeDisplayName (string) maxLength
            if(this.TypeDisplayName != null && this.TypeDisplayName.Length > 32)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TypeDisplayName, length must be less than 32.", new [] { "TypeDisplayName" });
            }

            // TypeId (int?) minimum
            if(this.TypeId < (int?)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TypeId, must be a value greater than or equal to 1.", new [] { "TypeId" });
            }

            yield break;
        }
    }

}
