/* 
 * RESTAPI Service
 *
 * RESTful API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// GetSamplesRFIDBatchByStreamResponseBody result type (default view)
    /// </summary>
    [DataContract]
    public partial class SamplerfidGetSamplesRFIDBatchByStreamResponseBody :  IEquatable<SamplerfidGetSamplesRFIDBatchByStreamResponseBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SamplerfidGetSamplesRFIDBatchByStreamResponseBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SamplerfidGetSamplesRFIDBatchByStreamResponseBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SamplerfidGetSamplesRFIDBatchByStreamResponseBody" /> class.
        /// </summary>
        /// <param name="hasMore">The value is set to true if there is more samples RFID to retrieve (required).</param>
        /// <param name="samples">samples (required).</param>
        public SamplerfidGetSamplesRFIDBatchByStreamResponseBody(bool? hasMore = default(bool?), StoredSampleRFIDResponseBodyCollection samples = default(StoredSampleRFIDResponseBodyCollection))
        {
            // to ensure "hasMore" is required (not null)
            if (hasMore == null)
            {
                throw new InvalidDataException("hasMore is a required property for SamplerfidGetSamplesRFIDBatchByStreamResponseBody and cannot be null");
            }
            else
            {
                this.HasMore = hasMore;
            }
            // to ensure "samples" is required (not null)
            if (samples == null)
            {
                throw new InvalidDataException("samples is a required property for SamplerfidGetSamplesRFIDBatchByStreamResponseBody and cannot be null");
            }
            else
            {
                this.Samples = samples;
            }
        }
        
        /// <summary>
        /// The value is set to true if there is more samples RFID to retrieve
        /// </summary>
        /// <value>The value is set to true if there is more samples RFID to retrieve</value>
        [DataMember(Name="hasMore", EmitDefaultValue=false)]
        public bool? HasMore { get; set; }

        /// <summary>
        /// Gets or Sets Samples
        /// </summary>
        [DataMember(Name="samples", EmitDefaultValue=false)]
        public StoredSampleRFIDResponseBodyCollection Samples { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SamplerfidGetSamplesRFIDBatchByStreamResponseBody {\n");
            sb.Append("  HasMore: ").Append(HasMore).Append("\n");
            sb.Append("  Samples: ").Append(Samples).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SamplerfidGetSamplesRFIDBatchByStreamResponseBody);
        }

        /// <summary>
        /// Returns true if SamplerfidGetSamplesRFIDBatchByStreamResponseBody instances are equal
        /// </summary>
        /// <param name="input">Instance of SamplerfidGetSamplesRFIDBatchByStreamResponseBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SamplerfidGetSamplesRFIDBatchByStreamResponseBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.HasMore == input.HasMore ||
                    (this.HasMore != null &&
                    this.HasMore.Equals(input.HasMore))
                ) && 
                (
                    this.Samples == input.Samples ||
                    (this.Samples != null &&
                    this.Samples.Equals(input.Samples))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.HasMore != null)
                    hashCode = hashCode * 59 + this.HasMore.GetHashCode();
                if (this.Samples != null)
                    hashCode = hashCode * 59 + this.Samples.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
