/* 
 * RESTAPI Service
 *
 * RESTful API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// GetGPSByDeviceIdResponseBody result type (default view)
    /// </summary>
    [DataContract]
    public partial class SamplegpsGetGPSByDeviceIDResponseBody :  IEquatable<SamplegpsGetGPSByDeviceIDResponseBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SamplegpsGetGPSByDeviceIDResponseBody" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SamplegpsGetGPSByDeviceIDResponseBody() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SamplegpsGetGPSByDeviceIDResponseBody" /> class.
        /// </summary>
        /// <param name="gps">gps (required).</param>
        /// <param name="id">ID is the unique id of the sample GPS. (required).</param>
        /// <param name="streamId">Stream ID (required).</param>
        public SamplegpsGetGPSByDeviceIDResponseBody(GPSResponseBody gps = default(GPSResponseBody), long? id = default(long?), int? streamId = default(int?))
        {
            // to ensure "gps" is required (not null)
            if (gps == null)
            {
                throw new InvalidDataException("gps is a required property for SamplegpsGetGPSByDeviceIDResponseBody and cannot be null");
            }
            else
            {
                this.Gps = gps;
            }
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for SamplegpsGetGPSByDeviceIDResponseBody and cannot be null");
            }
            else
            {
                this.Id = id;
            }
            // to ensure "streamId" is required (not null)
            if (streamId == null)
            {
                throw new InvalidDataException("streamId is a required property for SamplegpsGetGPSByDeviceIDResponseBody and cannot be null");
            }
            else
            {
                this.StreamId = streamId;
            }
        }
        
        /// <summary>
        /// Gets or Sets Gps
        /// </summary>
        [DataMember(Name="gps", EmitDefaultValue=false)]
        public GPSResponseBody Gps { get; set; }

        /// <summary>
        /// ID is the unique id of the sample GPS.
        /// </summary>
        /// <value>ID is the unique id of the sample GPS.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public long? Id { get; set; }

        /// <summary>
        /// Stream ID
        /// </summary>
        /// <value>Stream ID</value>
        [DataMember(Name="stream_id", EmitDefaultValue=false)]
        public int? StreamId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SamplegpsGetGPSByDeviceIDResponseBody {\n");
            sb.Append("  Gps: ").Append(Gps).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  StreamId: ").Append(StreamId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SamplegpsGetGPSByDeviceIDResponseBody);
        }

        /// <summary>
        /// Returns true if SamplegpsGetGPSByDeviceIDResponseBody instances are equal
        /// </summary>
        /// <param name="input">Instance of SamplegpsGetGPSByDeviceIDResponseBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SamplegpsGetGPSByDeviceIDResponseBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Gps == input.Gps ||
                    (this.Gps != null &&
                    this.Gps.Equals(input.Gps))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.StreamId == input.StreamId ||
                    (this.StreamId != null &&
                    this.StreamId.Equals(input.StreamId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Gps != null)
                    hashCode = hashCode * 59 + this.Gps.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.StreamId != null)
                    hashCode = hashCode * 59 + this.StreamId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // StreamId (int?) minimum
            if(this.StreamId < (int?)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for StreamId, must be a value greater than or equal to 1.", new [] { "StreamId" });
            }

            yield break;
        }
    }

}
