/* 
 * RESTAPI Service
 *
 * RESTful API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// StoredDeviceHealthResponse result type (default view)
    /// </summary>
    [DataContract]
    public partial class StoredDeviceHealthResponse :  IEquatable<StoredDeviceHealthResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StoredDeviceHealthResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StoredDeviceHealthResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StoredDeviceHealthResponse" /> class.
        /// </summary>
        /// <param name="counterTypeId">Counter type ID (required).</param>
        /// <param name="DeviceChildIdDefunct">Device ID of device health (required).</param>
        /// <param name="id">ID is the unique id of the device health. (required).</param>
        /// <param name="sampleDate">Date of sample (required).</param>
        /// <param name="value">Value (required).</param>
        public StoredDeviceHealthResponse(int? counterTypeId = default(int?), int? DeviceChildIdDefunct = default(int?), long? id = default(long?), DateTime? sampleDate = default(DateTime?), int? value = default(int?))
        {
            // to ensure "counterTypeId" is required (not null)
            if (counterTypeId == null)
            {
                throw new InvalidDataException("counterTypeId is a required property for StoredDeviceHealthResponse and cannot be null");
            }
            else
            {
                this.CounterTypeId = counterTypeId;
            }
            // to ensure "DeviceChildIdDefunct" is required (not null)
            if (DeviceChildIdDefunct == null)
            {
                throw new InvalidDataException("DeviceChildIdDefunct is a required property for StoredDeviceHealthResponse and cannot be null");
            }
            else
            {
                this.DeviceChildIdDefunct = DeviceChildIdDefunct;
            }
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for StoredDeviceHealthResponse and cannot be null");
            }
            else
            {
                this.Id = id;
            }
            // to ensure "sampleDate" is required (not null)
            if (sampleDate == null)
            {
                throw new InvalidDataException("sampleDate is a required property for StoredDeviceHealthResponse and cannot be null");
            }
            else
            {
                this.SampleDate = sampleDate;
            }
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new InvalidDataException("value is a required property for StoredDeviceHealthResponse and cannot be null");
            }
            else
            {
                this.Value = value;
            }
        }
        
        /// <summary>
        /// Counter type ID
        /// </summary>
        /// <value>Counter type ID</value>
        [DataMember(Name="counter_type_id", EmitDefaultValue=false)]
        public int? CounterTypeId { get; set; }

        /// <summary>
        /// Device ID of device health
        /// </summary>
        /// <value>Device ID of device health</value>
        [DataMember(Name="device_id", EmitDefaultValue=false)]
        public int? DeviceChildIdDefunct { get; set; }

        /// <summary>
        /// ID is the unique id of the device health.
        /// </summary>
        /// <value>ID is the unique id of the device health.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public long? Id { get; set; }

        /// <summary>
        /// Date of sample
        /// </summary>
        /// <value>Date of sample</value>
        [DataMember(Name="sample_date", EmitDefaultValue=false)]
        public DateTime? SampleDate { get; set; }

        /// <summary>
        /// Value
        /// </summary>
        /// <value>Value</value>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public int? Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StoredDeviceHealthResponse {\n");
            sb.Append("  CounterTypeId: ").Append(CounterTypeId).Append("\n");
            sb.Append("  DeviceChildIdDefunct: ").Append(DeviceChildIdDefunct).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  SampleDate: ").Append(SampleDate).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StoredDeviceHealthResponse);
        }

        /// <summary>
        /// Returns true if StoredDeviceHealthResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of StoredDeviceHealthResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StoredDeviceHealthResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CounterTypeId == input.CounterTypeId ||
                    (this.CounterTypeId != null &&
                    this.CounterTypeId.Equals(input.CounterTypeId))
                ) && 
                (
                    this.DeviceChildIdDefunct == input.DeviceChildIdDefunct ||
                    (this.DeviceChildIdDefunct != null &&
                    this.DeviceChildIdDefunct.Equals(input.DeviceChildIdDefunct))
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.SampleDate == input.SampleDate ||
                    (this.SampleDate != null &&
                    this.SampleDate.Equals(input.SampleDate))
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CounterTypeId != null)
                    hashCode = hashCode * 59 + this.CounterTypeId.GetHashCode();
                if (this.DeviceChildIdDefunct != null)
                    hashCode = hashCode * 59 + this.DeviceChildIdDefunct.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.SampleDate != null)
                    hashCode = hashCode * 59 + this.SampleDate.GetHashCode();
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CounterTypeId (int?) minimum
            if(this.CounterTypeId < (int?)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CounterTypeId, must be a value greater than or equal to 1.", new [] { "CounterTypeId" });
            }

            // DeviceChildIdDefunct (int?) minimum
            if(this.DeviceChildIdDefunct < (int?)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DeviceChildIdDefunct, must be a value greater than or equal to 1.", new [] { "DeviceChildIdDefunct" });
            }

            // Value (int?) minimum
            if(this.Value < (int?)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Value, must be a value greater than or equal to 1.", new [] { "Value" });
            }

            yield break;
        }
    }

}
