/* 
 * RESTAPI Service
 *
 * RESTful API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// StreamSetStreamCustomAttributeValuesRequestBody
    /// </summary>
    [DataContract]
    public partial class StreamSetStreamCustomAttributeValuesRequestBody :  IEquatable<StreamSetStreamCustomAttributeValuesRequestBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StreamSetStreamCustomAttributeValuesRequestBody" /> class.
        /// </summary>
        /// <param name="attributes">attributes.</param>
        public StreamSetStreamCustomAttributeValuesRequestBody(List<StoredStreamCustomAttributeValueRequestBody> attributes = default(List<StoredStreamCustomAttributeValueRequestBody>))
        {
            this.Attributes = attributes;
        }
        
        /// <summary>
        /// Gets or Sets Attributes
        /// </summary>
        [DataMember(Name="attributes", EmitDefaultValue=false)]
        public List<StoredStreamCustomAttributeValueRequestBody> Attributes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StreamSetStreamCustomAttributeValuesRequestBody {\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StreamSetStreamCustomAttributeValuesRequestBody);
        }

        /// <summary>
        /// Returns true if StreamSetStreamCustomAttributeValuesRequestBody instances are equal
        /// </summary>
        /// <param name="input">Instance of StreamSetStreamCustomAttributeValuesRequestBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StreamSetStreamCustomAttributeValuesRequestBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Attributes == input.Attributes ||
                    this.Attributes != null &&
                    this.Attributes.SequenceEqual(input.Attributes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Attributes != null)
                    hashCode = hashCode * 59 + this.Attributes.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
