/* 
 * RESTAPI Service
 *
 * RESTful API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ThresholdGetThresholdByStreamResponseBody
    /// </summary>
    [DataContract]
    public partial class ThresholdGetThresholdByStreamResponseBody :  IEquatable<ThresholdGetThresholdByStreamResponseBody>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ThresholdGetThresholdByStreamResponseBody" /> class.
        /// </summary>
        /// <param name="levels">levels.</param>
        public ThresholdGetThresholdByStreamResponseBody(StoredThresholdLevelResponseBodyCollection levels = default(StoredThresholdLevelResponseBodyCollection))
        {
            this.Levels = levels;
        }
        
        /// <summary>
        /// Gets or Sets Levels
        /// </summary>
        [DataMember(Name="levels", EmitDefaultValue=false)]
        public StoredThresholdLevelResponseBodyCollection Levels { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ThresholdGetThresholdByStreamResponseBody {\n");
            sb.Append("  Levels: ").Append(Levels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ThresholdGetThresholdByStreamResponseBody);
        }

        /// <summary>
        /// Returns true if ThresholdGetThresholdByStreamResponseBody instances are equal
        /// </summary>
        /// <param name="input">Instance of ThresholdGetThresholdByStreamResponseBody to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ThresholdGetThresholdByStreamResponseBody input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Levels == input.Levels ||
                    (this.Levels != null &&
                    this.Levels.Equals(input.Levels))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Levels != null)
                    hashCode = hashCode * 59 + this.Levels.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
